version: "3"
services:
    unbound:
        container_name: unbound-${UNBOUND_VER}
        image: unbound-${UNBOUND_VER}
        build: 
            context: ./unbound
            args:
                - VERSION=${UNBOUND_VER}
                - QMIN=${UNBOUND_QMIN}
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.1
#===============================================
    bind:
        container_name: bind-${BIND_VER}
        image: bind-${BIND_VER}
        build: 
            context: ./bind
            args:
                - VERSION=${BIND_VER}
                - QMIN=${BIND_QMIN}
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.2
#===============================================
    knot:
        container_name: knot-${KNOT_VER}
        image: knot-${KNOT_VER}
        build: 
            context: ./knot
            args:
                - VERSION=${KNOT_VER}
                - QMIN=${KNOT_QMIN}
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.3
#===============================================
    powerdns:
        container_name: powerdns-${POWERDNS_VER}
        image: powerdns-${POWERDNS_VER}
        build: 
            context: ./powerdns
            args:
                - VERSION=${POWERDNS_VER}
                - QMIN=${POWERDNS_QMIN}
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.4
#===============================================
    egress:
        container_name: egress
        image: egress
        build: 
            context: ./unbound
            args:
                - VERSION=1.17.1
                - QMIN=off
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.5
#===============================================
networks:
    resolver-lab:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/16
                  gateway: 10.0.0.1
