version: "3"
services:
    unbound:
        image: resolver-lab/unbound-${UNBOUND_VER}
        container_name: unbound-${UNBOUND_VER}
        environment:
            CONFIG: ${UNBOUND_CONF}
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.1
#===============================================
    bind:
        image: resolver-lab/bind-${BIND_VER}
        container_name: bind-${BIND_VER}
        environment:
            CONFIG: ${BIND_CONF}
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.2
#===============================================
    knot:
        image: resolver-lab/knot-${KNOT_VER}
        container_name: knot-${KNOT_VER}
        environment:
            CONFIG: ${KNOT_CONF}
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.3
#===============================================
    powerdns:
        image: resolver-lab/powerdns-${POWERDNS_VER}
        container_name: powerdns-${POWERDNS_VER}
        environment:
            CONFIG: ${POWERDNS_CONF}
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.4
#===============================================
    egress:
        image: resolver-lab/unbound-1.17.1
        container_name: egress
        environment:
            CONFIG: qmin-off
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.5
#===============================================
    fpdns:
        image: resolver-lab/fpdns.lab
        container_name: fpdns.lab
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.6
#===============================================
    oldqmin:
        cap_add:
            - NET_ADMIN # add two IPv4 addresses within container
        image: resolver-lab/qmin.lab
        container_name: oldqmin.lab
        environment:
            VERSION: old
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.7 # and 10.0.53.8
#===============================================
    newqmin:
        cap_add:
            - NET_ADMIN # add two IPv4 addresses within container
        image: resolver-lab/qmin.lab
        container_name: newqmin.lab
        environment:
            VERSION: new
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.9 # and 10.0.53.10
#===============================================
    auth:
        image: resolver-lab/ns1.lab
        container_name: ns1.lab
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.53
#===============================================
networks:
    resolver-lab:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/16
                  gateway: 10.0.0.1
