version: "3"
services:
    unbound:
        container_name: unbound-${UNBOUND_VER}
        image: unbound-${UNBOUND_VER}
        build: 
            context: ./unbound # path to Dockerfile
            args:
                - VERSION=${UNBOUND_VER}
                - QMIN=${UNBOUND_QMIN}
        tty: true
        networks:
            resolvernet:
                ipv4_address: 10.0.53.1
networks:
    resolvernet:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/16
                  gateway: 10.0.0.1
