version: "3"
services:
    unbound:
        container_name: unbound-${UNBOUND_VER}
        image: unbound-${UNBOUND_VER}
        build: 
            context: ./unbound/
            dockerfile: ${UNBOUND_DFILE}
            args:
                - VERSION=${UNBOUND_VER}
                - CONF=${UNBOUND_CONF}
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.1
#===============================================
    bind:
        container_name: bind-${BIND_VER}
        image: bind-${BIND_VER}
        build: 
            context: ./bind
            dockerfile: ${BIND_DFILE}
            args:
                - VERSION=${BIND_VER}
                - CONF=${BIND_CONF}
                - EXT=${BIND_EXT}
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.2
#===============================================
    knot:
        container_name: knot-${KNOT_VER}
        image: knot-${KNOT_VER}
        build: 
            context: ./knot
            dockerfile: ${KNOT_DFILE}
            args:
                - VERSION=${KNOT_VER}
                - CONF=${KNOT_CONF}
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.3
#===============================================
    powerdns:
        container_name: powerdns-${POWERDNS_VER}
        image: powerdns-${POWERDNS_VER}
        build: 
            context: ./powerdns
            dockerfile: ${POWERDNS_DFILE}
            args:
                - VERSION=${POWERDNS_VER}
                - CONF=${POWERDNS_CONF}
        tty: true
        stdin_open: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.4
#===============================================
    egress:
        container_name: egress
        image: egress
        build: 
            context: ./unbound
            dockerfile: default.Dockerfile
            args:
                - VERSION=1.17.1
                - CONF=qmin-off
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.5
#===============================================
    fpdns:
        container_name: fpdns
        image: fpdns
        build: 
            context: ./fpdns.auth
            dockerfile: Dockerfile
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.6
#===============================================
    oldqmin:
        cap_add:
            - NET_ADMIN # add two IPv4 addresses within container
        container_name: oldqmin
        image: oldqmin
        build: 
            context: ./qmin.auth
            dockerfile: Dockerfile
            args:
                - VERSION=old
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.7 # and 10.0.53.8
#===============================================
    newqmin:
        cap_add:
            - NET_ADMIN # add two IPv4 addresses within container
        container_name: newqmin
        image: newqmin
        build: 
            context: ./qmin.auth
            dockerfile: Dockerfile
            args:
                - VERSION=new
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.9 # and 10.0.53.10
#===============================================
    auth-tld:
        container_name: auth-tld
        image: auth-tld
        build: 
            context: ./ns1.auth
            dockerfile: Dockerfile
        tty: true
        networks:
            resolver-lab:
                ipv4_address: 10.0.53.53
#===============================================
networks:
    resolver-lab:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/16
                  gateway: 10.0.0.1
